; PlatformIO Project Configuration File

[platformio]
default_envs = esp32u_base_espnow

[env:esp32u_base_espnow]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ignore =
    mockPubSubClient
    mockLoraWan
    mockWiFi
build_unflags =
    -std=gnu++11
    -std=c++11
    -std=c++14
build_flags =
    -std=gnu++17
    -DCONNECT_USING_WIFI=1
    -DCONNECT_USING_4G=0
    -DFIRMWARE_ROLE_BASE=1
build_src_filter =
    +<main.cpp>
    +<functions/Rtcm_Frame_Reader.cpp>
    +<hardware/BaseEspnow_sender.cpp>
